name: Build and Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JFROG_READ_USER: ${{ secrets.JFROG_READ_USER }}
  JFROG_READ_TOKEN: ${{ secrets.JFROG_READ_TOKEN }}

jobs:
  build_and_test:
    runs-on: main

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Install Docker Compose v2 plugin
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL "https://github.com/docker/compose/releases/download/v2.36.2/docker-compose-$(uname -s)-$(uname -m)" -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          docker compose version

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: pre-commit
        run: make run-pre-commit

      - name: up
        run: make up

      - name: Create reports output folder
        run: mkdir -p /home/runner/work/${{ github.repository }}/reports

      - name: tests
        run: |
          docker compose run --rm --name helix.fhir.client.sdk -v /home/runner/work/${{ github.repository }}/reports:/reports dev pytest helix_fhir_client_sdk tests --tb=auto --junitxml=/reports/test-results.xml
          docker compose run --rm --name helix.fhir.client.sdk -v /home/runner/work/${{ github.repository }}/reports:/reports dev pytest tests_integration --tb=auto --junitxml=/reports/test-results-integration.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: /home/runner/work/${{ github.repository }}/reports/**/*.xml
        if: ${{ always() }}

      - name: Verify reports are generated
        if: ${{ always() }}
        run: ls -halt /home/runner/work/${{ github.repository }}/reports/

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@fc6576eced1f411ea48ab10e917d9cfce2960e29
        with:
          path: /home/runner/work/${{ github.repository }}/reports/*.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results
