name: Build and Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

#      - name: Docker Compose Setup
#        run: |
#          sudo apt-get install docker-compose-plugin
#          docker compose version

      - name: pre-commit
        run: make run-pre-commit

      # setup and install everything and run tests
      - name: up
        run: make up

      - name: Create reports output folder
        run: mkdir -p /home/runner/work/${{ github.repository }}/reports

      - name: tests
        run: |
          docker compose run --rm --name helix.fhir.client.sdk -v /home/runner/work/${{ github.repository }}/reports:/reports dev pytest tests --tb=auto --junitxml=/reports/test-results.xml
          docker compose run --rm --name helix.fhir.client.sdk -v /home/runner/work/${{ github.repository }}/reports:/reports dev pytest tests_integration --tb=auto --junitxml=/reports/test-results-integration.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: /home/runner/work/${{ github.repository }}/reports/**/*.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      # Publish all test results in the GitHub UI
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Pytest Report            # Name of the check run which will be created
          path: /home/runner/work/${{ github.repository }}/reports/**/*.xml    # Path to test results
          reporter: java-junit        # Format of test results
          fail-on-error: false        # Do not change the build status if errors are found
